In [4]:
# The pip install only works with python2!
#!pip install pyflann

In [5]:
from pyflann import *
import numpy as np

In [17]:
dataset = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])

print(dataset.shape[0],dataset.shape[1],'-dimensional points')

(3, 5, '-dimensional points')


In [18]:
testset = np.array(
    [[1., 1, 1, 1, 1],
     [90, 90, 10, 10, 1]
     ])

print(testset.shape)

(2, 5)


In [19]:
help(flann.nn)

Help on method nn in module pyflann.index:

nn(self, pts, qpts, num_neighbors=1, **kwargs) method of pyflann.index.FLANN instance
    Returns the num_neighbors nearest points in dataset for each point
    in testset.



In [11]:
flann = FLANN()
result, dists = flann.nn(dataset, testset, 2, algorithm="kmeans", branching=32, iterations=7, checks=16)

In [12]:
print(result)

[[0 1]
 [2 1]]


In [13]:
print(dists)

[[5.000e+00 2.480e+02]
 [6.640e+02 1.285e+04]]


In [8]:
dataset = np.random.rand(10000, 128)
testset = np.random.rand(1000, 128)

In [9]:
flann = FLANN()
result, dists = flann.nn(dataset, testset, 5, algorithm="kmeans", branching=32, iterations=7, checks=16)

print(result)
print(dists)

[[6972 8346  117 2989 3677]
 [7404 3760 7248 8049  282]
 [9651 2418 6997 7807 1087]
 ...
 [7966 1248 4883   93 4559]
 [1747 4530 2445  511 5351]
 [1267  919 6303 9067 5849]]
[[17.27968222 17.5466392  18.10378828 18.27071612 18.42279511]
 [15.66722268 15.69641734 16.05380229 16.3316637  16.79788037]
 [14.52281806 17.44009111 17.62912949 17.64109503 17.73273139]
 ...
 [16.44902738 18.22033482 19.06106755 19.14138765 19.22337921]
 [15.60080284 16.16688225 16.97112321 17.10837767 17.18038913]
 [15.68317774 15.97336985 16.15842306 16.229877   16.56302997]]
