Notes from
Fandango, Armando. Mastering TensorFlow 1.x: Advanced machine learning and deep learning concepts using TensorFlow 1.x and Keras (Kindle Locations 424-430). Packt Publishing. Kindle Edition. 

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#Get-an-Interactive-TensorFlow-Session" data-toc-modified-id="Get-an-Interactive-TensorFlow-Session-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Get an Interactive TensorFlow Session</a></span></li><li><span><a href="#Customary-Hello-TensorFlow-!!!" data-toc-modified-id="Customary-Hello-TensorFlow-!!!-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Customary Hello TensorFlow !!!</a></span></li><li><span><a href="#Constants" data-toc-modified-id="Constants-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Constants</a></span></li><li><span><a href="#Operations" data-toc-modified-id="Operations-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Operations</a></span></li><li><span><a href="#Placeholders" data-toc-modified-id="Placeholders-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Placeholders</a></span></li><li><span><a href="#Creating-Tensors-from-Existing-Objects" data-toc-modified-id="Creating-Tensors-from-Existing-Objects-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Creating Tensors from Existing Objects</a></span><ul class="toc-item"><li><span><a href="#0-Dimensional-Tensors-(Scalars)" data-toc-modified-id="0-Dimensional-Tensors-(Scalars)-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>0-Dimensional Tensors (Scalars)</a></span></li><li><span><a href="#1-Dimensional-Tensors-(Vectors)" data-toc-modified-id="1-Dimensional-Tensors-(Vectors)-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>1-Dimensional Tensors (Vectors)</a></span></li><li><span><a href="#2-Dimensional-Tensors-(Matrices)" data-toc-modified-id="2-Dimensional-Tensors-(Matrices)-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>2-Dimensional Tensors (Matrices)</a></span></li><li><span><a href="#3-Dimensional-Tensors" data-toc-modified-id="3-Dimensional-Tensors-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>3-Dimensional Tensors</a></span></li></ul></li><li><span><a href="#Variables" data-toc-modified-id="Variables-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Variables</a></span></li><li><span><a href="#Creating-Tensors-from-Library-Functions" data-toc-modified-id="Creating-Tensors-from-Library-Functions-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Creating Tensors from Library Functions</a></span></li><li><span><a href="#Close-the-interactive-session" data-toc-modified-id="Close-the-interactive-session-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Close the interactive session</a></span></li><li><span><a href="#Computation-Graphs" data-toc-modified-id="Computation-Graphs-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Computation Graphs</a></span><ul class="toc-item"><li><span><a href="#Building-and-Running-simple-computation-graph" data-toc-modified-id="Building-and-Running-simple-computation-graph-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Building and Running simple computation graph</a></span></li><li><span><a href="#Graph-on-Compute-Devices" data-toc-modified-id="Graph-on-Compute-Devices-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>Graph on Compute Devices</a></span></li><li><span><a href="#Executing-Graph-g-as-Default" data-toc-modified-id="Executing-Graph-g-as-Default-10.3"><span class="toc-item-num">10.3&nbsp;&nbsp;</span>Executing Graph g as Default</a></span></li></ul></li><li><span><a href="#TensorBoard" data-toc-modified-id="TensorBoard-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>TensorBoard</a></span></li></ul></div>

# TensorFlow 101 <a class="tocSkip">

In [2]:
import tensorflow as tf
import numpy as np

# Get an Interactive TensorFlow Session 

In [3]:
# InteractiveSession becomes the default session
tfs = tf.InteractiveSession()

# Customary Hello TensorFlow !!!
execute the constant in TF session:

In [4]:
hello = tf.constant("Hello TensorFlow !!")
print(tfs.run(hello))

b'Hello TensorFlow !!'


Tensors can be created in the following ways: <br/>
<br/>
By defining constants, operations, and variables, and passing the values to their constructor. <br/>
By defining placeholders and passing the values to session.run(). <br/>
By converting Python objects such as scalar values, lists, and NumPy arrays with the tf.convert_to_tensor() function.


# Constants

In [5]:
c1 = tf.constant(5, name='x')
c2 = tf.constant(6.0, name='y')
c3 = tf.constant(7.0, tf.float32, name='z')
print('c1 (x): ', c1)
print('c2 (y): ', c2)
print('c3 (z): ', c3)

c1 (x):  Tensor("x:0", shape=(), dtype=int32)
c2 (y):  Tensor("y:0", shape=(), dtype=float32)
c3 (z):  Tensor("z:0", shape=(), dtype=float32)


In order to print the values of these constants, we have to execute them in a TensorFlow session with the tfs.run() command:

In [6]:
print('run([c1,c2,c3]) : ', tfs.run([c1, c2, c3]))

run([c1,c2,c3]) :  [5, 6.0, 7.0]


## TF Datatypes

tf.float16 16-bit half-precision floating point <br/>
tf.float32 32-bit single-precision floating point <br/>
tf.float64 64-bit double-precision floating point <br/>
tf.bfloat16 16-bit truncated floating point <br/>
tf.complex64 64-bit single-precision complex <br/>
tf.complex128 128-bit double-precision complex <br/>

tf.int8 8-bit signed integer <br/>
tf.uint8 8-bit unsigned integer  <br/>
tf.uint16 16-bit unsigned integer <br/>
tf.int16 16-bit signed integer <br/>
tf.int32 32-bit signed integer <br/>
tf.int64 64-bit signed integer <br/>

tf.bool Boolean <br/>
tf.string String <br/>
tf.qint8 Quantized 8-bit signed integer <br/> 
tf.quint8 Quantized 8-bit unsigned integer <br/>
tf.qint16 Quantized 16-bit signed integer <br/>
tf.quint16 Quantized 16-bit unsigned integer <br/>
tf.qint32 Quantized 32-bit signed integer <br/>
tf.resource Handle to a mutable resource<br/>



# Difference between Session and Interactive Session

The only difference between Session() and InteractiveSession() is that the session created with InteractiveSession() becomes the default session. Thus, we do not need to specify the session context. For example, we have a session object, tfs, and a constant object, hello. If tfs is an InteractiveSession() object, then we can evaluate hello with the code hello.eval(). If tfs is a Session() object, then we have to use either tfs.hello.eval() or a with block.


In [7]:
hello = tf.constant("hi",name="helloConstant")
hello.eval()

b'hi'

# Operations

In [8]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)

When we print op1 and op2, we find that they are defined as Tensors

In [9]:
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  Tensor("Add:0", shape=(), dtype=float32)
op2 :  Tensor("Mul:0", shape=(), dtype=float32)


To print the value of these operations, we have to run them in our TensorFlow session:

In [10]:
print('run(op1) : ', tfs.run(op1))
print('run(op2) : ', tfs.run(op2))

run(op1) :  13.0
run(op2) :  42.0


## The following table lists some of the built-in operations:

Arithmetic operations: tf.add, tf.subtract, tf.multiply, tf.scalar_mul, tf.div, tf.divide, tf.truediv, tf.floordiv, tf.realdiv, tf.truncatediv, tf.floor_div, tf.truncatemod, tf.floormod, tf.mod, tf.cross <br/>
<br/>
Basic math operations: tf.add_n, tf.abs, tf.negative, tf.sign, tf.reciprocal, tf.square, tf.round, tf.sqrt, tf.rsqrt, tf.pow, tf.exp, tf.expm1, tf.log, tf.log1p, tf.ceil, tf.floor, tf.maximum, tf.minimum, tf.cos, tf.sin, tf.lbeta, tf.tan, tf.acos, tf.asin, tf.atan, tf.lgamma, tf.digamma, tf.erf, tf.erfc, tf.igamma, tf.squared_difference, tf.igammac, tf.zeta, tf.polygamma, tf.betainc, tf.rint<br/>
<br/>
Tensor math operations tf.tensordot <br/> 
<br/>
Complex number operations tf.complex, tf.conj, tf.imag, tf.real <br/>
<br/>
String operations tf.string_to_hash_bucket_fast, tf.string_to_hash_bucket_strong, tf.as_string, tf.encode_base64, tf.decode_base64, tf.reduce_join, tf.string_join, tf.string_split, tf.substr, tf.string_to_hash_bucket
 
 

# Placeholders

While constants allow us to provide a value at the time of defining the tensor, the placeholders allow us to create tensors whose values can be provided at runtime. TensorFlow provides the tf.placeholder() function with the following signature to create placeholders: 
<br/>
<br/>
tf.placeholder( dtype, shape = None, name = None)
 

In [11]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1 : ', p1)
print('p2 : ', p2)

p1 :  Tensor("Placeholder:0", dtype=float32)
p2 :  Tensor("Placeholder_1:0", dtype=float32)


In [12]:
op4 = p1 * p2  # shorthand for tf.multiply(p1, p2)

In [13]:
print(op4)

Tensor("mul_1:0", dtype=float32)


In [14]:
print('run(op4,{p1:2.0, p2:3.0}) : ',tfs.run(op4,{p1:2.0, p2:3.0}))

run(op4,{p1:2.0, p2:3.0}) :  6.0


We can also specify the dictionary using the feed_dict parameter in the run() operation:

In [15]:
print('run(op4,feed_dict = {p1:3.0, p2:4.0}) : ',
      tfs.run(op4, feed_dict={p1: 3.0, p2: 4.0}))

run(op4,feed_dict = {p1:3.0, p2:4.0}) :  12.0


In [16]:
print('run(op4,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}):',
      tfs.run(op4, feed_dict={p1: [2.0, 3.0, 4.0], p2: [3.0, 4.0, 5.0]}))

run(op4,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}): [ 6. 12. 20.]


# Creating Tensors from Existing Objects
We can create tensors from python objects such as lists and numpy arrays using the tf.convert_to_tensor() operation with the following signature: <br/>
<br/>

tf.convert_to_tensor( value, dtype = None, name = None, preferred_dtype = None )



## 0-Dimensional Tensors (Scalars)
Create and print a 0-D Tensor:
 

In [17]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print('tf_t : ', tf_t)
print('run(tf_t) : \n', tfs.run(tf_t))

tf_t :  Tensor("Const_1:0", shape=(), dtype=float64)
run(tf_t) : 
 5.0


## 1-Dimensional Tensors (Vectors)

In [18]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print("a1dim Shape : ", a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[2] : ', tf_t[2])
print('run(tf_t) : \n', tfs.run(tf_t))

a1dim Shape :  (5,)
tf_t :  Tensor("Const_2:0", shape=(5,), dtype=float64)
tf_t[0] :  Tensor("strided_slice:0", shape=(), dtype=float64)
tf_t[2] :  Tensor("strided_slice_1:0", shape=(), dtype=float64)
run(tf_t) : 
 [1.   2.   3.   4.   5.99]


## 2-Dimensional Tensors (Matrices)

In [19]:
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print("a2dim Shape : ", a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])
print('run(tf_t) : \n', tfs.run(tf_t))

a2dim Shape :  (3, 5)
tf_t :  Tensor("Const_3:0", shape=(3, 5), dtype=float64)
tf_t[0][0] :  Tensor("strided_slice_3:0", shape=(), dtype=float64)
tf_t[1][2] :  Tensor("strided_slice_5:0", shape=(), dtype=float64)
run(tf_t) : 
 [[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


## 3-Dimensional Tensors

In [20]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print("a3dim Shape : ", a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : \n', tfs.run(tf_t))

a3dim Shape :  (2, 2, 2)
tf_t :  Tensor("Const_4:0", shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  Tensor("strided_slice_8:0", shape=(), dtype=float64)
tf_t[1][1][1] :  Tensor("strided_slice_11:0", shape=(), dtype=float64)
run(tf_t) : 
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


# Variables
Variables are objects that can be updated during the executation of the program

So far, we have seen how to create tensor objects of various kinds: constants, operations, and placeholders. <br/>
<br/>
While working with TensorFlow to build and train models, you will often need to hold the values of parameters in a memory location that can be updated at runtime. That memory location is identified by variables in TensorFlow.<br/> 
<br/>
In TensorFlow, variables are tensor objects that hold values that can be modified during the execution of the program.



tf.placeholder defines input data that does not change over time <br/> 
tf.Variable defines variable values that are modified over time <br/>

tf.placeholder does not need an initial value at the time of definition <br/>
tf.Variable needs an initial value at the time of definition <br/>


In [21]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b

print("w:", w)
print("x:", x)
print("b:", b)
print("y:", y)

w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
x: Tensor("Placeholder_2:0", dtype=float32)
b: <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>
y: Tensor("add_1:0", dtype=float32)


The output shows that x is a placeholder tensor and y is an operation tensor, while w and b are variables with shape (1,) and data type float32.

Before you can use the variables in a TensorFlow session, they have to be initialized. <br/>
You can initialize a single variable by running its initializer operation. For example, let's initialize the variable w: <br/>
tfs.run( w.initializer) 


In [22]:
tfs.run( w.initializer)

However, in practice, we use a convenience function provided by the TensorFlow to initialize all the variables: <br/>tfs.run( tf.global_variables_initializer()) 

In [23]:
tfs.run( tf.global_variables_initializer()) 

You can also use it outside of tfs.run:

In [24]:
# before using a variable, it has to be initialized
# initialize and print the variable y
tf.global_variables_initializer().run()
print('run(y,{x:[1,2,3,4]}) : ', tfs.run(y, {x: [1, 2, 3, 4]}))

run(y,{x:[1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


You can also use the tf.variables_initializer() function to initialize only a set of variables.


# Creating Tensors from Library Functions

Tensors can also be generated from various TensorFlow functions. These generated tensors can either be assigned to a constant or a variable, or provided to their constructor at the time of initialization.


In [25]:
a = tf.zeros((100,))
print(tfs.run(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


zeros( shape, dtype = tf.float32, name = None ) Creates a tensor of the provided shape, with all elements set to zero <br/>
<br/>
zeros_like( tensor, dtype = None, name = None, optimize = True ) Creates a tensor of the same shape as the argument, with all elements set to zero <br/>
<br/>
ones( shape, dtype = tf.float32, name = None ) Creates a tensor of the provided shape, with all elements set to one <br/>
<br/>
ones_like( tensor, dtype = None, name = None, optimize = True ) Creates a tensor of the same shape as the argument, with all elements set to one <br/>
<br/>
fill( dims, value, name = None ) Creates a tensor of the shape as the dims argument, with all elements set to value;<br/>


In [26]:
a = tf.fill([100], 3) 
print(tfs.run(a))

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


## Populating tensor elements with sequences

lin_space( start, stop, num, name = None ) Generates a 1-D tensor from a sequence of num numbers within the range [start, stop]. The tensor has the same data type as the start argument. 

In [27]:
a = tf.lin_space(1.0,100.0,10)
print(tfs.run(a))

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


range( limit, delta = 1, dtype = None, name =' range' ) <br/>
range( start, limit, delta = 1, dtype = None, name =' range' ) <br/>
<br/>
Generates a 1-D tensor from a sequence of numbers within the range [start, limit], with the increments of delta. <br/>
<br/>
If the dtype argument is not specified, then the tensor has the same data type as the start argument. This function comes in two versions. In the second version, if the start argument is omitted, then start becomes number 0. <br/>
<br/>
For example, a = tf.range( 1,91,10) generates a tensor with values [1,11,21,31,41,51,61,71,81]. Note that the value of the limit argument, that is 91, is not included in the final generated sequence. <br/>


In [28]:
a = tf.range( 1,91,10)
print(tfs.run(a))

[ 1 11 21 31 41 51 61 71 81]


## Populating tensor elements with a random distribution


TensorFlow provides us with the functions to generate tensors filled with random valued distributions. <br/> 

The distributions generated are affected by the graph-level or the operation-level seed. <br/>

The graph-level seed is set using tf.set_random_seed, while the operation-level seed is given as the argument seed in all of the random distribution functions. <br/>

If no seed is specified, then a random seed is used.



random_normal( shape, mean = 0.0, stddev = 1.0, dtype = tf.float32, seed = None, name = None ) Generates a tensor of the specified shape, filled with values from a normal distribution: normal( mean, stddev).


truncated_normal( shape, mean = 0.0, stddev = 1.0, dtype = tf.float32, seed = None, name = None ) Generates a tensor of the specified shape, filled with values from a truncated normal distribution: normal( mean, stddev). Truncated means that the values returned are always at a distance less than two standard deviations from the mean.



random_uniform( shape, minval = 0, maxval = None, dtype = tf.float32, seed = None, name = None ) Generates a tensor of the specified shape, filled with values from a uniform distribution: uniform([ minval, maxval)). 

<br/>
random_gamma( shape, alpha, beta = None, dtype = tf.float32, seed = None, name = None ) Generates tensors of the specified shape, filled with values from gamma distributions: gamma( alpha, beta).



### get_variable()

If you define a variable with a name that has been defined before, then TensorFlow throws an exception. Hence, it is convenient to use the tf.get_variable() function instead of tf.Variable(). The function tf.get_variable() returns the existing variable with the same name if it exists, and creates the variable with the specified shape and initializer if it does not exist. For example:

In [29]:
w = tf.get_variable( name ='w', dtype = tf.float32, initializer =[.3]) 

In [30]:
b = tf.get_variable( name ='b', dtype = tf.float32, initializer =[-.3])

The initializer can be a tensor or list of values as shown in above examples or one of the inbuilt initializers: <br/>
<br/>
tf.constant_initializer <br/>
tf.random_normal_initializer <br/>
tf.truncated_normal_initializer <br/>
tf.random_uniform_initializer <br/>
tf.uniform_unit_scaling_initializer <br/> 
tf.zeros_initializer <br/>
tf.ones_initializer <br/>
tf.orthogonal_initializer <br/>

In distributed TensorFlow where we can run the code across machines, the tf.get_variable() gives us global variables. To get the local variables TensorFlow has a function with similar signature: tf.get_local_variable(). 


Sharing or Reusing Variables: Getting already-defined variables promotes reuse. 
However, an exception will be thrown if the reuse flags are not set by using tf.variable_scope.reuse_variable() or tf.variable.scope( reuse = True).


# Close the interactive session

In [31]:
tfs.close()

# Computation Graphs

Computation graph is the basic unit of computation in TensorFlow. A computation graph is made up of nodes and edges. Each node represents an operation (tf.Operation) and each edge represents a tensor (tf.Tensor) that gets transferred between the nodes. <br/>

You create the graph with nodes representing variables, constants, placeholders, and operations and feed it to TensorFlow. <br/>

TensorFlow programs are made up of two kinds of operations on computation graphs: Building the computation graph Running the computation graph <br/>

The TensorFlow comes with a default graph. Unless another graph is explicitly specified, a new node gets implicitly added to the default graph. We can get explicit access to the default graph using the following command: graph = tf.get_default_graph() <br/>



In [32]:
graph = tf.get_default_graph()
print(graph)

## Building and Running simple computation graph

In [33]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b
output = 0

with tf.Session() as tfs:
    # initialize and print the variable y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})
print('output : ', output)

output :  [0.         0.3        0.6        0.90000004]


Creating and using a session in the with block ensures that the session is automatically closed when the block is finished. Otherwise, the session has to be explicitly closed with the tfs.close() command, where tfs is the session name.

## Graph on Compute Devices
A graph can be divided into multiple parts, and each part can be placed and executed on seaparate devices such as cpu or gpu.

In [34]:
# We can list all the devices available for graph executation
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15813908792753277838
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 11280557671
locality {
  bus_id: 1
  links {
  }
}
incarnation: 10173791928984445297
physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7"
]


By default CPU: 0 denotes all the CPU's available to TensorFlow.

Let us enable the logging of variable placement by defining a config object, set the log_device_placement property to true, and then pass this config object to the session as follows:

In [35]:
tf.reset_default_graph()

# Define model parameters
w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
# Define model input and output
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

output [0.         0.3        0.6        0.90000004]


This write this on the console
Device mapping:  
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7    
w: (VariableV2): /job:localhost/replica:0/task:0/device:GPU:0  
w/Assign: (Assign): /job:localhost/replica:0/task:0/device:GPU:0  
w/read: (Identity): /job:localhost/replica:0/task:0/device:GPU:0  
b: (VariableV2): /job:localhost/replica:0/task:0/device:GPU:0  
b/Assign: (Assign): /job:localhost/replica:0/task:0/device:GPU:0  
b/read: (Identity): /job:localhost/replica:0/task:0/device:GPU:0  
mul: (Mul): /job:localhost/replica:0/task:0/device:GPU:0  
add: (Add): /job:localhost/replica:0/task:0/device:GPU:0  
init: (NoOp): /job:localhost/replica:0/task:0/device:GPU:0  
Const: (Const): /job:localhost/replica:0/task:0/device:GPU:0  
w/initial_value: (Const): /job:localhost/replica:0/task:0/device:GPU:0  
Const_1: (Const): /job:localhost/replica:0/task:0/device:GPU:0  
b/initial_value: (Const): /job:localhost/replica:0/task:0/device:GPU:0  
x: (Placeholder): /job:localhost/replica:0/task:0/device:GPU:0  
 
 
Thus by default, the TensorFlow creates the variable and operations nodes on a device where it can get the highest performance. The variables and operations can be placed on specific devices by using tf.device() function.


In [36]:
# let us place the graph on the CPU instead of GPU
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Define model parameters
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Define model input and output
    x = tf.placeholder(name='x', dtype=tf.float32)
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

output [0.         0.3        0.6        0.90000004]


Device mapping:  
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7  
w: (VariableV2): /job:localhost/replica:0/task:0/device:CPU:0  
w/Assign: (Assign): /job:localhost/replica:0/task:0/device:CPU:0  
w/read: (Identity): /job:localhost/replica:0/task:0/device:CPU:0  
b: (VariableV2): /job:localhost/replica:0/task:0/device:CPU:0  
b/Assign: (Assign): /job:localhost/replica:0/task:0/device:CPU:0  
b/read: (Identity): /job:localhost/replica:0/task:0/device:CPU:0  
mul: (Mul): /job:localhost/replica:0/task:0/device:CPU:0  
add: (Add): /job:localhost/replica:0/task:0/device:CPU:0  
init: (NoOp): /job:localhost/replica:0/task:0/device:CPU:0  
Const: (Const): /job:localhost/replica:0/task:0/device:CPU:0  
w/initial_value: (Const): /job:localhost/replica:0/task:0/device:CPU:0  
Const_1: (Const): /job:localhost/replica:0/task:0/device:CPU:0  
b/initial_value: (Const): /job:localhost/replica:0/task:0/device:CPU:0  
x: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0  
  

TensorFlow follows these simple rules, also known as the simple placement, for placing the variables on the devices:   

If the graph was previously run, then the node is left on the device where it was placed earlier   
Else If the tf.device() block is used, then the node is placed on the specified device    
Else If the GPU is present then the node is placed on the first available GPU    
Else If the GPU is not present then the node is placed on the CPU   



# GPU memory handling 

When you start running the TensorFlow session, by default it grabs all of the GPU memory, even if you place the operations and variables only on one GPU in a multi-GPU system. 

If you try to run another session at the same time, you will get out of memory error.   

This can be solved in multiple ways: For multi-GPU systems, set the environment variable   

CUDA_VISIBLE_DEVICES = < list of device idx > os.environ[' CUDA_VISIBLE_DEVICES'] =' 0' 

The code executed after this setting will be able to grab all of the memory of only the visible GPU.   

When you do not want the session to grab all of the memory of the GPU, then you can use the config option per_process_gpu_memory_fraction to allocate a percentage of memory:  

config.gpu_options.per_process_gpu_memory_fraction = 0.5 

This will allocate 50% of the memory of all the GPU devices. 

You can also combine both of the above strategies, i.e. make only a percentage along with making only some of the GPU visible to the process. 

You can also limit the TensorFlow process to grab only the minimum required memory at the start of the process. 

As the process executes further, you can set a config option to allow the growth of this memory. 

config.gpu_options.allow_growth = True 

This option only allows for the allocated memory to grow, but the memory is never released back.



## Executing Graph g as Default

Multiple graphs You can create your own graphs separate from the default graph and execute them in a session. However, creating and executing multiple graphs is not recommended, as you cannot directly pass data in between graphs.  

Hence, the recommended approach is to have multiple subgraphs in a single graph. 

In case you wish to use your own graph instead of the default graph, you can do so with the tf.graph() command. 

Here is an example where we create our own graph, g, and execute it as the default graph:



In [37]:
g = tf.Graph()
output = 0

# Assume Linear Model y = w * x + b

with g.as_default():
    # Define model parameters
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Define model input and output
    x = tf.placeholder(tf.float32)
    y = w * x + b

with tf.Session(graph=g) as tfs:
    # initialize and print the variable y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})

print('output : ', output)

output :  [0.         0.3        0.6        0.90000004]


# TensorBoard

In [38]:
import tensorflow as tf
import numpy as np

# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], name='w', dtype=tf.float32)
b = tf.Variable([-.3], name='b', dtype=tf.float32)
# Define model input and output
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b



Initialize a session, and within the context of this session, do the following steps:  

Initialize global variables   

Create tf.summary.FileWriter that would create the output in the tflogs folder with the events from the default graph   

Fetch the value of node y, effectively executing our linear model  



In [39]:
with tf.Session() as tfs:
    tf.global_variables_initializer().run()
    writer = tf.summary.FileWriter('tflogs', tfs.graph)
    print('run(y,{x:3}) : ', tfs.run(y, feed_dict={x: 3}))

run(y,{x:3}) :  [0.6]


In [40]:
# execute: tensorboard --logdir='tflogs'

As the program executes, the logs are collected in the tflogs folder that would be used by TensorBoard for visualization. 


In the terminal start the environment that runs tensorflow, e.g.  

 source activate tensorflow_p36

Go to the folder that has the log directory, e.g. ‘tflogs’ .  Then run
 tensorboard --logdir='tflogs'

If you use AWS EC2: Open port 6006 (or the port you assigned to the visualization web server) on your EC2 instance.

In the Amazon EC2 console, choose Network & Security, then choose Security Groups.  
For Security Group, choose the one that was used for your instance. Choose the Inbound tab, and choose Edit.

Choose Add Rule.

In the new row, type the followings:

Type : Custom TCP Rule  
Protocol: TCP  
Port Range: 6006 (or the port that you assigned to the visualization server)  
Source: Anywhere (0.0.0.0/0,::/0)  

To open the web page for the TensorBoard visualizations use the public IP or DNS address of the EC2 instance and the port that you opened for TensorBoard: http:// YourInstancePublicDNS:6006

For example:  http://ec2-18-188-214-178.us-east-2.compute.amazonaws.com:6006


TensorBoard works by reading log files generated by TensorFlow. Thus, we need to modify the programming model defined here to incorporate additional operation nodes that would produce the information in the logs that we want to visualize using TensorBoard.

Create summary nodes. Attach summary operations from the tf.summary package to the nodes that output the values that you wish to collect and analyze. Run the summary nodes along with running your model nodes.

Generally, you would use the convenience function, tf.summary.merge_all(), to merge all the summary nodes into one summary node. Then executing this merged node would basically execute all the summary nodes.

The merged summary node produces a serialized Summary ProtocolBuffers object containing the union of all the summaries. Write the event logs to disk by passing the Summary ProtocolBuffers object to a tf.summary.FileWriter object.